In [1]:
import pandas as pd

In [5]:
df = pd.read_excel('myExcelFile.xlsx',sheet_name='my_data') #Wprowadzenie parametru określającego nazwę zakładki, z której Pandas postara się pobrać dane, jest opcjonalne. Domyślnie wczytana będzie zawartość pierwszej zakładki.

In [6]:
df.to_excel('myNewExcelFile.xlsx', sheet_name='my_new_data')

In [8]:
df.head()

   A   B    C
0  0   0    0
1  1   1   50
2  2   4  100
3  3   9  150
4  4  16  200

In [9]:
df.tail()

     A    B    C
6    6   36  300
7    7   49  350
8    8   64  400
9    9   81  450
10  10  100  500

In [10]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       11 non-null     int64
 1   B       11 non-null     int64
 2   C       11 non-null     int64
dtypes: int64(3)
memory usage: 396.0 bytes

df.describe()

In [ ]:
df.columns(