In [3]:
import numpy as np
import pandas as pd
from scipy.stats import skew
from IPython.display import display

In [4]:
# Ustawienie losowości (powtarzalność wyników) - zeby zawsze dostac te same liczby kiedy bedziemy runowac 
np.random.seed(42)

In [5]:
# Parametry rozkładu normalnego
mean = 3
std_dev = 1

In [6]:
# Generowanie danych
data_100 = np.random.normal(mean, std_dev, 100)
data_10000 = np.random.normal(mean, std_dev, 10000)

In [7]:
# liczenie statystyk opisowych

In [29]:
def descriptive_stats(data):
    q0 = np.min(data)
    q1 = np.percentile(data, 25)
    q2 = np.median(data)
    q3 = np.percentile(data, 75)
    q4 = np.max(data)
    
    iqr = q3 - q1

    stats = {
        "Średnia": np.mean(data),
        "Mediana": np.median(data),
        "Odchylenie standardowe": np.std(data, ddof=1),
        "Wariancja": np.var(data, ddof=1),
        "Skośność": skew(data),
        "Zakres": q4 - q0,
        "IQR": iqr,
        "Q0 (min)": q0,
        "Q1": q1,
        "Q2 (mediana)": q2,
        "Q3": q3,
        "Q4 (max)": q4
    }
        
    return pd.DataFrame(
            stats.items(),
            columns=["Statystyka", "Wartość"]
                )

In [30]:
descriptive_stats(data_100)

                Statystyka   Wartość
0                  Średnia  2.896153
1                  Mediana  2.873044
2   Odchylenie standardowe  0.908168
3                Wariancja  0.824770
4                 Skośność -0.175268
5                   Zakres  4.472023
6                      IQR  1.006858
7                 Q0 (min)  0.380255
8                       Q1  2.399094
9             Q2 (mediana)  2.873044
10                      Q3  3.405952
11                Q4 (max)  4.852278

In [31]:
descriptive_stats(data_10000)

                Statystyka   Wartość
0                  Średnia  2.998821
1                  Mediana  2.998835
2   Odchylenie standardowe  1.003741
3                Wariancja  1.007497
4                 Skośność  0.002161
5                   Zakres  7.848638
6                      IQR  1.345597
7                 Q0 (min) -0.922400
8                       Q1  2.326435
9             Q2 (mediana)  2.998835
10                      Q3  3.672032
11                Q4 (max)  6.926238

# wnioski

Im większa próba, tym wyniki są bliższe temu, czego oczekujemy dla rozkładu normalnego. Przy 100 obserwacjach widać jeszcze przypadkowe odchylenia – średnia, mediana czy skośność odbiegają od idealnych wartości. Przy 10 000 danych wszystko się stabilizuje: średnia i mediana są bliskie 3, skośność prawie zerowa, a wariancja bliska 1. Widać też, że większa próba daje większy zakres, bo łatwiej trafić na wartości skrajne, ale środek danych (kwartyle i IQR) pozostaje dość stabilny.